site_name: Fire.js Documentation
pages:
- Home: index.md
- Statics: statics.md
- Classes:
  - AFArray: AFArray.md
  - Dim4: Dim4.md
  - Seq: Seq.md
- Functions:
  - Managing Devices: devices.md
theme: united
repo_url: https://github.com/unbornchikken/fire-js